### ISSUE TITLE
[FEAT] 코어데이터 객체 이름 변경 및 객체 속성 재구성

### ISSUE THREAD

**Issue by SH0123** [SH0123/BookAndMe#1]
## 💡 Issue
코어데이터 객체 이름 변경 및 객체 속성 재구성

## 📝  todo
- [ ] 객체 E-R 다이어그램 작성
- [ ] 객체 속성 재구성
- [ ] 객체 이름 변경 (모호한 이름으로 인해 코드 작성시 혼란 발생)
